OZO 「お象」: Related functions
Related functions
Database connection
Description
Connection related functions.
Functions
template<typename T >
constexpr decltype(auto) ozo::unwrap_connection (T &&conn) noexcept
Unwrap connection if wrapped with Nullable.
template<typename Connection >
auto ozo::get_native_handle (const Connection &conn) noexcept
PostgreSQL native connection handle.
template<typename Connection >
auto ozo::get_executor (const Connection &conn) noexcept
Executor for connection related asynchronous operations.
template<typename T >
bool ozo::connection_bad (const T &conn) noexcept
Indicates if connection state is bad.
template<typename T >
bool ozo::connection_good (const T &conn) noexcept
Indicates if connection state is not bad.
template<typename Connection >
std::string_view ozo::error_message (const Connection &conn)
Gives native libpq error message.
template<typename T >
const auto & ozo::get_error_context (const T &conn)
Additional error context getter.
template<typename T , typename Ctx >
void ozo::set_error_context (T &conn, Ctx &&ctx)
Additional error context setter.
template<typename T >
void ozo::reset_error_context (T &conn)
Reset additional error context.
template<typename T >
decltype(auto) ozo::get_oid_map (T &&conn) noexcept
Access to a connection OID map.
template<typename T >
decltype(auto) ozo::get_statistics (T &&conn) noexcept
Access to a Connection statistics.
template<typename Connection >
std::string_view ozo::get_database (const Connection &conn)
Get the database name of the active connection.
template<typename Connection >
std::string_view ozo::get_host (const Connection &conn)
Get the host connected of the active connection.
template<typename Connection >
std::string_view ozo::get_port (const Connection &conn)
Get the port connected of the active connection.
template<typename Connection >
std::string_view ozo::get_user (const Connection &conn)
Get the user name of the active connection.
template<typename Connection >
std::string_view ozo::get_password (const Connection &conn)
Get the password of the active connection.
template<typename T , typename TimeConstraint , typename CompletionToken >
decltype(auto) ozo::get_connection (T &&provider, TimeConstraint time_constraint, CompletionToken &&token)
Get a #Connection from #ConnectionProvider.
template<typename T , typename CompletionToken >
decltype(auto) ozo::get_connection (T &&provider, CompletionToken &&token)
Get a connection from provider with no time constains.
template<typename Connection >
error_code ozo::close_connection (Connection &&conn)
Close connection to the database immediately.
template<typename Connection >
auto ozo::defer_close_connection (Connection *conn)
Close connection to the database when leaving the scope.
template<typename... Ts>
constexpr auto ozo::get_transaction_isolation_level (const impl::transaction< Ts... > &transaction)
Retrieve's a transactions isolation level.
template<typename... Ts>
constexpr auto ozo::get_transaction_mode (const impl::transaction< Ts... > &transaction)
Retrieve's a transactions transaction mode.
template<typename... Ts>
constexpr auto ozo::get_transaction_deferrability (const impl::transaction< Ts... > &transaction)
Retrieve's a transactions deferrability.
template<typename Connection >
transaction_status ozo::get_transaction_status (Connection &&conn)
Returns current status of a #Connection object.
template<typename OidMap = empty_oid_map, typename Statistics = no_statistics>
auto make_connection_info (std::string conn_str, const OidMap &oid_map=OidMap{}, Statistics statistics=Statistics{})
Constructs ozo::connection_info #ConnectionSource.
template<typename Source >
auto make_connection_pool (Source &&source, const connection_pool_config &config)
Connection pool construct helper function.
Function Documentation
close_connection()
template<typename Connection > error_code ozo::close_connection (Connection && conn)
Close connection to the database immediately.
This function closes connection to the database immediately.
Note
No query cancel operation will be made while closing connection. Use the function with attention - non cancelled query can still produce a work on server-side and consume resources. So it is better to use ozo::cancel() function.
Parameters
conn — #Connection to be closed
References ozo::unwrap_connection().
Referenced by ozo::defer_close_connection().
connection_bad()
template<typename T > bool ozo::connection_bad (const T & conn) noexcept
Indicates if connection state is bad.
If conn is #Nullable - checks for null state first via operator !().
Parameters
conn — #Connection object to check
Returns
true if connection is in bad or null state, false - otherwise.
Referenced by ozo::connection_good().
connection_good()
template<typename T > bool ozo::connection_good (const T & conn) noexcept
Indicates if connection state is not bad.
See ozo::connection_bad for details.
Parameters
conn — #Connection to check
Returns
false if connection is in bad state, true - otherwise
References ozo::connection_bad().
defer_close_connection()
template<typename Connection > auto ozo::defer_close_connection (Connection * conn)
Close connection to the database when leaving the scope.
This function creates RAII guard object which calls ozo::close_connection() at the end of its scope. If nullptr is passed as argument or connection is null recursive no ozo::close_connection() would be made.
Parameters
conn — pointer on a #Connection to be closed.
Example
{
    auto guard = defer_close_connection(should_be_closed ? std::addressof(conn) : nullptr);
    // Process the connection
}
References ozo::close_connection(), ozo::Connection, and ozo::is_null_recursive().
Referenced by ozo::failover::basic_try< Options, Context >::get_next_try().
error_message()
template<typename Connection > std::string_view ozo::error_message (const Connection & conn)
Gives native libpq error message.
Underlying libpq provides additional textual context for different errors which can be while interacting via connection. This function gives access for such messages.
Parameters
conn — #Connection to get message from
Returns
std::string_view contains a message
References ozo::get_native_handle(), and ozo::is_null_recursive().
get_connection() [1/2]
template<typename T , typename CompletionToken > decltype(auto) ozo::get_connection (T && provider, CompletionToken && token)
Get a connection from provider with no time constains.
This function is time constrain free shortcut to ozo::get_connection() function. Its call is equal to ozo::get_connection(provider, ozo::none, token) call.
Note
The function does not particitate in ADL since could be implemented via functional object.
Parameters
provider — #ConnectionProvider to get connection from.
token — operation #CompletionToken.
Returns
deduced from #CompletionToken.
get_connection() [2/2]
template<typename T , typename TimeConstraint , typename CompletionToken > decltype(auto) ozo::get_connection (T && provider, TimeConstraint time_constraint, CompletionToken && token)
Get a #Connection from #ConnectionProvider.
Retrives #Connection from #ConnectionProvider. There is built-in customization for #Connection which provides connection itself and resets it's error context.
Note
The function does not particitate in ADL since could be implemented via functional object.
Parameters
provider — #ConnectionProvider to get connection from.
time_constraint — #TimeConstraint for the operation.
token — operation #CompletionToken.
Returns
deduced from #CompletionToken.
Customization point
This is a customization point of #ConnectionProvider. By default #ConnectionProvider should have async_get_connection() member function with signature:
template <typename TimeConstraint>
void async_get_connection(TimeConstraint t, Handler&& h);
This behaviour can be customized via async_get_connection_impl specialization. E.g. for custom implementation of #Connection customization may looks like this (exposition only):
template <typename TimeConstrain, typename ...Ts>
struct async_get_connection_impl<MyConnection<Ts...>, TimeConstrain> {
    template <typename Conn, typename Handler>
    static constexpr void apply(Conn&& c, TimeConstraint t, Handler&& h) {
        c->prepareForNextOp();
        async_get_connection_impl_default<MyConnection<Ts...>, TimeConstrain>::apply(
            std::forward<Conn>(c), t, std::forward<Handler>(h)
        );
    }
};
get_database()
template<typename Connection > std::string_view ozo::get_database (const Connection & conn)
Get the database name of the active connection.
See documentation for the underlying PQdb function for additional information.
Note
Connection should not be is null recursive.
Parameters
conn — active connection to a database.
Returns
std::string_view — string view with database name.
References ozo::get_native_handle().
get_error_context()
template<typename T > const auto& ozo::get_error_context (const T & conn)
Additional error context getter.
In addition to libpq OZO provides its own error context. This is a getter for such a context. Please be sure that the connection is not in the null state via ozo::is_null_recursive() function.
See also
ozo::set_error_context(), ozo::reset_error_context(), ozo::is_null_recursive()
Parameters
conn — #Connection to get context from, should not be in null state
Returns
std::string contains a context
get_executor()
template<typename Connection > auto ozo::get_executor (const Connection & conn) noexcept
Executor for connection related asynchronous operations.
This executor must be used to schedule all the asynchronous operations related to #Connection to allow timer-based timeouts works for all of the operations.
Parameters
conn — #Connection object
Returns
executor of socket stream object of the connection
References ozo::unwrap_connection().
get_host()
template<typename Connection > std::string_view ozo::get_host (const Connection & conn)
Get the host connected of the active connection.
See documentation for the underlying PQhost function for additional information.
Note
Connection should not be is null recursive.
Parameters
conn — active connection to a database.
Returns
std::string_view — string view with host.
References ozo::get_native_handle().
get_native_handle()
template<typename Connection > auto ozo::get_native_handle (const Connection & conn) noexcept
PostgreSQL native connection handle.
In common cases you do not need this function. It's purpose is to support extention and customization of the library. So if you want do extend or customize some behaviour via original libpq calls this is what you really need. In other cases this is not the function what you are looking for.
Parameters
conn — #Connection object
Returns
native handle
References ozo::unwrap_connection().
Referenced by ozo::error_message(), ozo::get_cancel_handle(), ozo::get_database(), ozo::get_host(), ozo::get_password(), ozo::get_port(), and ozo::get_user().
get_oid_map()
template<typename T > decltype(auto) ozo::get_oid_map (T && conn) noexcept
Access to a connection OID map.
This function gives access to a connection OID map, which represents mapping of custom types to its' OIDs in a database connected to. Please be sure that the connection is not in the null state via ozo::is_null_recursive() function.
Parameters
conn — #Connection to access OID map, should not be in null state
Returns
OID map of the Connection
get_password()
template<typename Connection > std::string_view ozo::get_password (const Connection & conn)
Get the password of the active connection.
See documentation for the underlying PQpass function for additional information.
Note
Connection should not be is null recursive.
Parameters
conn — active connection to a database.
Returns
std::string_view — string view with password.
References ozo::get_native_handle().
get_port()
template<typename Connection > std::string_view ozo::get_port (const Connection & conn)
Get the port connected of the active connection.
See documentation for the underlying PQport function for additional information.
Note
Connection should not be is null recursive.
Parameters
conn — active connection to a database.
Returns
std::string_view — string view with port.
References ozo::get_native_handle().
get_statistics()
template<typename T > decltype(auto) ozo::get_statistics (T && conn) noexcept
Access to a Connection statistics.
Note
This feature is not implemented yet
Please be sure that the connection is not in the null state via ozo::is_null_recursive() function.
Parameters
conn — #Connection to access statistics, should not be in null state
Returns
statistics of the Connection
get_transaction_deferrability()
template<typename... Ts> constexpr auto ozo::get_transaction_deferrability (const impl::transaction< Ts... > & transaction) constexpr
Retrieve's a transactions deferrability.
Deferrability is usually indicated using an instance of ozo::deferrable_mode, but can also be any other type with a compile-time static ::value convertible to bool. ozo::none indicates no explicit deferrability was set.
Parameters
transaction transaction to get the deferrability from
Returns
ozo::deferrable_mode (or any bool-convertible std::integral_constant) — if the deferrability has been set
ozo::none — if no deferrability has been set
References ozo::transaction_options::deferrability, ozo::get_option(), ozo::none, and ozo::transaction.
get_transaction_isolation_level()
template<typename... Ts> constexpr auto ozo::get_transaction_isolation_level (const impl::transaction< Ts... > & transaction) constexpr
Retrieve's a transactions isolation level.
The isolation level can either be an instance of one of the child types of ozo::isolation_level or ozo::none if no level was explicitly set.
Parameters
transaction transaction to get the isolation level from
Returns
sub type of ozo::isolation_level — if the transaction isolation level has been set
ozo::none — if no isolation level has been set
References ozo::get_option(), ozo::transaction_options::isolation_level, ozo::none, and ozo::transaction.
get_transaction_mode()
template<typename... Ts> constexpr auto ozo::get_transaction_mode (const impl::transaction< Ts... > & transaction) constexpr
Retrieve's a transactions transaction mode.
The mode can either be an instance of one of the child types of ozo::transaction_mode or ozo::none if mode was set explicitly set.
Parameters
transaction transaction to get the transaction mode from
Returns
sub type of ozo::transaction_mode — if the transaction mode has been set
ozo::none — if no transaction mode has been specified
References ozo::get_option(), ozo::transaction_options::mode, ozo::none, and ozo::transaction.
get_transaction_status()
template<typename Connection > transaction_status ozo::get_transaction_status (Connection && conn)
Returns current status of a #Connection object.
Returns current status of specified #Connection. If the #Connection is #Nullable in null-state returns ozo::transaction_status::unknown. In other case it returns value associated with libpq connection transaction status.
Parameters
conn — #Connection
Returns
transaction_status — status of the #Connection
Exceptions
std::invalid_argument — in case of unsupported value returned by libpq function. It is better to use -Werror compiler flag to prevent such possability by checking enumeration coverage in the switch-case statement.
get_user()
template<typename Connection > std::string_view ozo::get_user (const Connection & conn)
Get the user name of the active connection.
See documentation for the underlying PQuser function for additional information.
Note
Connection should not be is null recursive.
Parameters
conn — active connection to a database.
Returns
std::string_view — string view with user name.
References ozo::get_native_handle().
make_connection_info()
template<typename OidMap = empty_oid_map, typename Statistics = no_statistics> auto make_connection_info (std::string conn_str, const OidMap & oid_map = OidMap{}, Statistics statistics = Statistics{}) related
Constructs ozo::connection_info #ConnectionSource.
Parameters
conn_str — standard libpq connection string.
OidMap — oid map for user defined types.
statistics — statistics to collect for a connection.
Returns
ozo::connection_info specialization.
make_connection_pool()
template<typename Source > auto make_connection_pool (Source && source, const connection_pool_config & config) related
Connection pool construct helper function.
Helper function which creates connection pool based on #ConnectionSource and configuration parameters.
Parameters
source — #ConnectionSource object which is being used to create connection to a database.
config — pool configuration.
Returns
ozo::connection_pool object
reset_error_context()
template<typename T > void ozo::reset_error_context (T & conn)
Reset additional error context.
This function resets additional error context to its default value. Please be sure that the connection is not in the null state via ozo::is_null_recursive() function.
See also
ozo::set_error_context(), ozo::get_error_context(), ozo::is_null_recursive()
Parameters
conn — #Connection to reset context, should not be in null state
set_error_context()
template<typename T , typename Ctx > void ozo::set_error_context (T & conn, Ctx && ctx)
Additional error context setter.
In addition to libpq OZO provides its own error context. This is a setter for such a context. Please be sure that the connection is not in the null state via ozo::is_null_recursive() function.
See also
ozo::get_error_context(), ozo::reset_error_context(), ozo::is_null_recursive()
Parameters
conn — #Connection to set context to
ctx — context to set, now only std::string is supported
Referenced by ozo::connection< OidMap, Statistics >::assign().
unwrap_connection()
template<typename T > constexpr decltype(auto) ozo::unwrap_connection (T && conn) constexpr noexcept
Unwrap connection if wrapped with Nullable.
Unwraps wrapped connection recursively. Returns unwrapped connection object.
Customization Point
This is customization point for the Connection enhancement. To customize it it is better to specialize ozo::unwrap_connection_impl template for custom type. E.g. such overload is used for the ozo::impl::pooled_connection of this library. The deafult implementation of the function is perfect forwarding. And may look like this (for exposition only - actual implementation may be different):
template <typename T>
struct unwrap_connection_impl {
    template <typename Conn>
    static constexpr decltype(auto) apply(Conn&& conn) noexcept {
        return std::forward<Conn>(conn);
    }
};
If you are specialize the template for your own parameterized connection wrapper implementation do not forget to call unwrap_connection for the underlying connection type. E.g.:
template <typename T>
struct unwrap_connection_impl<CustomWrapper<T>>{
    template <typename Conn>
    static constexpr decltype(auto) apply(Conn&& conn) noexcept {
        return unwrap_connection(conn.underlying());
    }
};
Function overload works as well, but it is safer to specialize the template.
Parameters
conn — wrapped or unwrapped Connection
Returns
unwrapped #Connection object reference
Referenced by ozo::close_connection(), ozo::get_executor(), and ozo::get_native_handle().